### ISSUE TITLE
.где я shows the room for dead players

### ISSUE THREAD

**Issue by head47** [CreativeeBlackWolf/dobl-whoami-bot#44]
If a dead player invokes the `.где я` command, the bot shows their location in the room, though it should answer with `Ты мёртв`.

Steps to reproduce:
1. Create a dead player object, assign it to yourself
2. Invoke `.где я`

Actual output: the room's ASCII representation
Expected output: `Ты мёртв`

**Comment by CreativeeBlackWolf** [comment]
fixed
